### ISSUE TITLE
Whats the idea?

### ISSUE THREAD

**Issue by jesperordrup** [ProfessorFarnsworth/HTML-5-File-Upload#5]
Hi Professor,

What's the idea compared to the build in?

best
Jesper

**Comment by ProfessorFarnsworth** [comment]
Hi Jesper,

well the main idea is to get a better feedback for large file uploads. At the moment you just see that there is something uploading and you don't know when its done.

Best regards
Farnsworth

**Comment by bjarnef** [comment]
I agree for this. Unfortunately there has not been implemented feedback (progressbar/status) in the core yet. Furthermore when some images fails to upload (e.g. because of max limit) it is just ignored, so it would be nice to tell the editor/user that it failed to upload. Maybe you could handle a exception that might get returned from the server or check against the web.config before it try uploading the file, so it is proactive.

**Comment by jesperordrup** [comment]
Thx. Thats good points. Should be added to the core datatype even

**Comment by bjarnef** [comment]
Yes sure :) .. vote for it http://issues.umbraco.org/issue/U4-4802 :+1:

**Comment by ProfessorFarnsworth** [comment]
@bjarnef Yeah I've almost implemented something like this. My idea is to warn the user even before it fails. ;) The plan is to display the error when the file is dropped into the dropzone. ;)

@jesperordrup Yeah that would be kinda cool. It's probably already on there todo list for version 8. But I thought it would be cool to have it a bit earlier :)
